diff -Bsq /etc/httpd/conf.d/000_init_ootb_vars.conf etc/httpd/conf.d/000_init_ootb_vars.conf
diff -Bsq /etc/httpd/conf.d/001_init_ams_vars.conf etc/httpd/conf.d/001_init_ams_vars.conf
diff -Bsq /etc/httpd/conf.d/available_vhosts/aem_author.vhost etc/httpd/conf.d/available_vhosts/aem_author.vhost
diff -Bsq /etc/httpd/conf.d/available_vhosts/aem_flush.vhost etc/httpd/conf.d/available_vhosts/aem_flush.vhost
diff -Bsq /etc/httpd/conf.d/available_vhosts/aem_flush_author.vhost etc/httpd/conf.d/available_vhosts/aem_flush_author.vhost
diff -Bsq /etc/httpd/conf.d/available_vhosts/aem_publish.vhost etc/httpd/conf.d/available_vhosts/aem_publish.vhost
diff -Bsq /etc/httpd/conf.d/available_vhosts/ams_lc.vhost etc/httpd/conf.d/available_vhosts/ams_lc.vhost
diff -Bsq /etc/httpd/conf.d/dispatcher_vhost.conf etc/httpd/conf.d/dispatcher_vhost.conf
diff -Bsq /etc/httpd/conf.d/logformat.conf etc/httpd/conf.d/logformat.conf
diff -Bsq /etc/httpd/conf.d/mimetypes3d.conf etc/httpd/conf.d/mimetypes3d.conf
diff -Bsq /etc/httpd/conf.d/remoteip.conf etc/httpd/conf.d/remoteip.conf
diff -Bsq /etc/httpd/conf.d/rewrites/base_rewrite.rules etc/httpd/conf.d/rewrites/base_rewrite.rules
diff -Bsq /etc/httpd/conf.d/rewrites/xforwarded_forcessl_rewrite.rules etc/httpd/conf.d/rewrites/xforwarded_forcessl_rewrite.rules
diff -Bsq /etc/httpd/conf.d/security.conf etc/httpd/conf.d/security.conf
diff -Bsq /etc/httpd/conf.d/variables/ams_default.vars etc/httpd/conf.d/variables/ams_default.vars
diff -Bsq /etc/httpd/conf.d/variables/ootb.vars etc/httpd/conf.d/variables/ootb.vars
diff -Bsq /etc/httpd/conf.d/whitelists/000_base_whitelist.rules etc/httpd/conf.d/whitelists/000_base_whitelist.rules
diff -Bsq /etc/httpd/conf.dispatcher.d/available_farms/*_ams_catchall_farm.any etc/httpd/conf.dispatcher.d/available_farms/*_ams_catchall_farm.any
diff -Bsq /etc/httpd/conf.dispatcher.d/available_farms/*_ams_author_flush_farm.any etc/httpd/conf.dispatcher.d/available_farms/*_ams_author_flush_farm.any
diff -Bsq /etc/httpd/conf.dispatcher.d/available_farms/*_ams_publish_flush_farm.any etc/httpd/conf.dispatcher.d/available_farms/*_ams_publish_flush_farm.any
diff -Bsq /etc/httpd/conf.dispatcher.d/available_farms/*_ams_author_farm.any etc/httpd/conf.dispatcher.d/available_farms/*_ams_author_farm.any
diff -Bsq /etc/httpd/conf.dispatcher.d/available_farms/*_ams_lc_farm.any etc/httpd/conf.dispatcher.d/available_farms/*_ams_lc_farm.any
diff -Bsq /etc/httpd/conf.dispatcher.d/available_farms/*_ams_publish_farm.any etc/httpd/conf.dispatcher.d/available_farms/*_ams_publish_farm.any
diff -Bsq /etc/httpd/conf.dispatcher.d/cache/ams_author_cache.any etc/httpd/conf.dispatcher.d/cache/ams_author_cache.any
diff -Bsq /etc/httpd/conf.dispatcher.d/cache/ams_author_invalidate_allowed.any etc/httpd/conf.dispatcher.d/cache/ams_author_invalidate_allowed.any
diff -Bsq /etc/httpd/conf.dispatcher.d/cache/ams_publish_cache.any etc/httpd/conf.dispatcher.d/cache/ams_publish_cache.any
diff -Bsq /etc/httpd/conf.dispatcher.d/cache/ams_publish_invalidate_allowed.any etc/httpd/conf.dispatcher.d/cache/ams_publish_invalidate_allowed.any
diff -Bsq /etc/httpd/conf.dispatcher.d/clientheaders/ams_author_clientheaders.any etc/httpd/conf.dispatcher.d/clientheaders/ams_author_clientheaders.any
diff -Bsq /etc/httpd/conf.dispatcher.d/clientheaders/ams_common_clientheaders.any etc/httpd/conf.dispatcher.d/clientheaders/ams_common_clientheaders.any
diff -Bsq /etc/httpd/conf.dispatcher.d/clientheaders/ams_lc_clientheaders.any etc/httpd/conf.dispatcher.d/clientheaders/ams_lc_clientheaders.any
diff -Bsq /etc/httpd/conf.dispatcher.d/clientheaders/ams_publish_clientheaders.any etc/httpd/conf.dispatcher.d/clientheaders/ams_publish_clientheaders.any
diff -Bsq /etc/httpd/conf.dispatcher.d/dispatcher.any etc/httpd/conf.dispatcher.d/dispatcher.any
diff -Bsq /etc/httpd/conf.dispatcher.d/filters/ams_author_filters.any etc/httpd/conf.dispatcher.d/filters/ams_author_filters.any
diff -Bsq /etc/httpd/conf.dispatcher.d/filters/ams_lc_filters.any etc/httpd/conf.dispatcher.d/filters/ams_lc_filters.any
diff -Bsq /etc/httpd/conf.dispatcher.d/filters/ams_publish_filters.any etc/httpd/conf.dispatcher.d/filters/ams_publish_filters.any
diff -Bsq /etc/httpd/conf.dispatcher.d/renders/ams_author_renders.any etc/httpd/conf.dispatcher.d/renders/ams_author_renders.any
diff -Bsq /etc/httpd/conf.dispatcher.d/renders/ams_lc_renders.any etc/httpd/conf.dispatcher.d/renders/ams_lc_renders.any
diff -Bsq /etc/httpd/conf.dispatcher.d/renders/ams_publish_renders.any etc/httpd/conf.dispatcher.d/renders/ams_publish_renders.any
diff -Bsq /etc/httpd/conf.dispatcher.d/vhosts/ams_author_vhosts.any etc/httpd/conf.dispatcher.d/vhosts/ams_author_vhosts.any
diff -Bsq /etc/httpd/conf.dispatcher.d/vhosts/ams_lc_vhosts.any etc/httpd/conf.dispatcher.d/vhosts/ams_lc_vhosts.any
diff -Bsq /etc/httpd/conf.dispatcher.d/vhosts/ams_publish_vhosts.any etc/httpd/conf.dispatcher.d/vhosts/ams_publish_vhosts.any
diff -Bsq /etc/sysconfig/httpd.rpmnew etc/sysconfig/httpd.rpmnew
